version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "kind/dependencies"
      - "component/cdk"

  - package-ecosystem: "pip"
    directory: "/src/backend/queue_agent"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "kind/dependencies"
      - "component/queue-agent"
