stackName: "SdOnEKS" # Name of stack
modelBucketArn: 'arn:aws:s3:::dummy-bucket' # ARN of S3 bucket for model storage. Models file should be manual populated into the bucket.
APIGW:
  stageName: prod
  throttle:
    rateLimit: 30
    burstLimit: 50
modelsRuntime:
- name: "sdruntime1" # Name of runtime, should be unique
  namespace: "default"  # Namespace of runtime, suggest deploy different runtimes on seperate namespaces
  modelFilename: "" # (SD Web UI only) Model for this runtime. Model should be stored in /stable-diffusion of S3 bucket. Request will be routed by model filename.
  dynamicModel: false # (SD Web UI only) Enable dynamic model. This runtime will accept all requests. Then, the runtime will load model by request.
  type: "sdwebui" # Specify type of runtime. Different type of runtime represents different API Spec.
#  chartRepository: "" # Path of Helm chart if you choose to bring your own charts. Protocol (oci:// or https:// )should be added as a prefix of repository.
#  chartVersion: "" # Version of Helm chart.
  extraValues:
    karpenter:
      nodeTemplate:
        amiFamily: Bottlerocket
        dataVolume:
          volumeSize: 80Gi
          volumeType: gp3
          deleteOnTermination: true
          iops: 4000
          throughput: 1000
#          snapshotID: # EBS Snapshot ID with format snap-<snapshotid>
      provisioner:
        instanceType:
        - "g5.xlarge" # List of allowed instance type for Karpenter provisioning.
        - "g5.2xlarge"
        capacityType: # Allowed purchase mode for instances
          onDemand: true
          spot: false
    runtime:
#      inferenceApi:
#        image:
#          repository: <account_id>.dkr.ecr.<region>.amazonaws.com/sd-on-eks/inference-api # Image Repository of stable diffusion runtime.
#          tag: latest
#      queueAgent:
#        image:
#          repository: <account_id>.dkr.ecr.<region>.amazonaws.com/sd-on-eks/queue-agent # Image Repository of queue agent.
#          tag: latest
      scaling:
        queueLength: 10 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 60 # The period (in seconds) to wait after the last message before scaling down.
