{{- if .Values.runtime.scaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "sdchart.fullname" . }}-keda-trigger-auth-aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
  {{- if .Values.runtime.labels }}
  {{- toYaml .Values.runtime.labels | nindent 4 }}
  {{- end }}
spec:
  podIdentity:
    provider: aws-eks
{{- end }}