---
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required SageMaker Parameters
        Parameters:
          - NotebookInstanceType
          - GithubRepo
          - EBSSize
Parameters:
  NotebookInstanceType:
    AllowedValues:
      - ml.m5.xlarge
      - ml.t3.medium
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.m5.xlarge
    Description: Select Instance type for the SageMaker Notebook
    Type: String
  GithubRepo:
    Type: String
    Default: "https://github.com/aws-samples/stable-diffusion-on-eks.git"
    Description: Github Repository
  EBSSize: 
    Type: Number
    Default: 50
    Description: EBS Size Default Size is 50GB
Resources:
  ExecutionRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
# NOTEBOOK -----------------------------------------------------
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref 'NotebookInstanceType'
      RoleArn: !GetAtt ExecutionRole.Arn
      VolumeSizeInGB: !Ref 'EBSSize'
      LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
  BasicNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              cd /home/ec2-user/SageMaker
              git clone --recurse-submodules -j8 ${GithubRepo}
              echo "c.NotebookApp.terminado_settings={'shell_command': ['/bin/bash']}" | tee -a /home/ec2-user/.jupyter/jupyter_notebook_config.py >/dev/null
              sudo chown -R ec2-user:ec2-user /home/ec2-user/SageMaker
              echo "export s3uri=${S3Bucket}" >> /etc/profile.d/jupyter-env.sh
              sudo systemctl restart jupyter-server --no-block
# END NOTEBOOK -------------------------------------------------

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Need to define a static BucketName due to a circular dependency with the AWS::SNS::TopicPolicy
      BucketName: 
        !Sub 
          - 'sd-models-${AWS::Region}-${RandomGUID}'
          - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: BucketOwnerFullControl    

Outputs:
  Repo:
    Value: !Sub ${GithubRepo}
  NotebookInstanceLab:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstance.NotebookInstanceName}?view=lab"
    Description: Notebook Instance Lab
  S3Bucket:
    Value: !Sub ${S3Bucket}