apiVersion: v1
entries:
  sd-on-eks:
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-01T02:02:16.898561506Z"
    description: Stable Diffusion on EKS
    digest: 05ea4d1576ea3dc09a4dd3b0c18c715db3b77b05ee99a94a0c49433cff64bc7f
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-02-26T05:05:33.64171305Z"
    description: Stable Diffusion on EKS
    digest: 88792a2062341eb0a943a239fefe3df5f9ce8522f723b5d7cdbd19a514076b8b
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-01T02:02:16.897648013Z"
