apiVersion: v1
entries:
  sd-on-eks:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-04-10T16:00:11.561278434Z"
    description: Stable Diffusion on EKS
    digest: ec3eddf28390daa4d44a572d511c703429e3b909a1ce22e7073ef54aa04accb3
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-03-11T09:46:17.757731708Z"
    description: Stable Diffusion on EKS
    digest: c27aa1a98d6b80ca2d2ed656cc6128da368275347cb97e7bcc3ce2efd0ae546d
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-02-26T05:05:33.64171305Z"
    description: Stable Diffusion on EKS
    digest: 88792a2062341eb0a943a239fefe3df5f9ce8522f723b5d7cdbd19a514076b8b
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-0.1.0.tgz
    version: 0.1.0
generated: "2024-04-10T16:00:11.560584395Z"
