openapi: 3.0.3
info:
  title: SD on EKS
  version: v1alpha2
  x-logo:
    url: ""
servers:
  - url: http://localhost:8080/
    description: ""
paths:
  /task:
    summary: Submit task to SD on EKS runtimes
    post:
      requestBody:
        description: "Content of image generating task"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      operationId: SubmitTask
      responses:
        '200':
          description: Successful response, task is accepted
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  id:
                    type: string
                    description: Task ID
                    example: "abc"
                  runtime:
                    type: string
                    description: Selected runtime
                    example: "sdruntime1"
                  output_location:
                    type: string
                    description: Location of output file
                    example: "s3://sdoneksstack-outputs3bucket/abc"
      security:
      - apikey: []
externalDocs:
  description: Usage introduction
  url: >-
    https://aws-samples.github.io/stable-diffusion-on-eks/zh/implementation-guide/usage/
tags: []
security: []
components:
  schemas:
    Task:
      type: object
      properties:
        task:
          type: object
          properties:
            metadata:
              type: object
              properties:
                id:
                  type: string
                  description: Task ID
                  example: "abc"
                runtime:
                  type: string
                  description: Runtime used in this task, should match with installed runtime.
                  example: sdruntime1
                tasktype:
                  description: Type of task. Should be "text-to-image" or "image-to-image" for SD Web UI, and "pipeline" for ComfyUI
                  enum:
                    - text-to-image
                    - image-to-image
                    - pipeline
                  example: "text-to-image"
                  type: string
                prefix:
                  type: string
                  description: Prefix for output file store
                  example: "/output"    
                context:
                  type: object
                  description: All content in context will be brought to callback
                  example: ""
            content:
              type: object
              example: ""
  securitySchemes:
    apikey:
      type: apiKey
      description: API Key generated by AWS API Gateway
      name: x-api-key
      in: header
