openapi: 3.0.3
info:
  title: SD on EKS
  version: v1alpha1
  x-logo:
    url: ""
servers:
  - url: http://localhost:8080/v1alpha1
    description: ""
paths:
  /:
    summary: Submit task to SD on EKS runtimes
    post:
      requestBody:
        description: "Content of image generating task"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      operationId: SubmitTask
      responses:
        '200':
          description: Successful response, task is accepted
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  id_task:
                    type: string
                    description: Task ID
                    example: "abc"
                  task:
                    description: Type of task.
                    example: "text-to-image"
                    type: string
                  sd_model_checkpoint:
                    type: string
                    description: Selected model
                    example: "v1-5-pruned-emaonly.safetensors"
                  output_location:
                    type: string
                    description: Location of output file
                    example: "s3://sdoneksstack-outputs3bucket/abc"
      security:
      - apikey: {}
externalDocs:
  description: Usage introduction
  url: >-
    https://aws-samples.github.io/stable-diffusion-on-eks/zh/implementation-guide/usage/
tags: []
security: []
components:
  schemas:
    Task:
      type: object
      properties:
        task:
          type: object
          properties:
            alwayson_scripts:
                type: object
                properties:
                    task:
                        description: Type of task. Should be "text-to-image" or "image-to-image" for SD Web UI
                        enum:
                            - text-to-image
                            - image-to-image
                        example: "text-to-image"
                        type: string
                    sd_model_checkpoint:
                        description: Checkpoint used in the task
                        example: "v1-5-pruned-emaonly.safetensors"
                        type: string
                    id_task:
                        description: Task ID
                        example: "v1-5-pruned-emaonly.safetensors"
                        type: string
                    uid:
                        type: string
                        description: User ID
                        example: "abc"
                    save_dir:
                        type: string
                        description: Directory stored in s3 bucket, should be "output" only
                        example: output
            prompt:
                type: string
                example: ""
            steps:
                type: integer
                example: 16
            height:
                type: integer
                example: 512
            width:
                type: integer
                example: 512
  securitySchemes:
    apikey:
      type: apiKey
      description: API Key generated by AWS API Gateway
      name: x-api-key
      in: header