site_name: Stable Diffusion on Amazon EKS
site_url: https://yubingjiaocn.github.io/stable-diffusion-on-eks/
repo_url: https://github.com/aws-samples/stable-diffusion-on-eks/
repo_name: aws-samples/stable-diffusion-on-eks
docs_dir: .
site_dir: ../site/
theme:
  name: material
  features:
    - navigation.tabs
  icon:
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  copyright: Copyright &copy; 2023 Amazon Web Services
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

plugins:
  - search
  - include-markdown
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg