site_name: Stable Diffusion on Amazon EKS
site_url: https://yubingjiaocn.github.io/stable-diffusion-on-eks/
repo_url: https://github.com/aws-samples/stable-diffusion-on-eks/
repo_name: aws-samples/stable-diffusion-on-eks
docs_dir: .
site_dir: ../site/
theme:
  name: material
  features:
    - navigation.tabs
  icon:
      repo: fontawesome/brands/github
  language: en

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  copyright: Copyright &copy; 2023 Amazon Web Services

plugins:
  - search
  - include-markdown
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 实施指南:
      - 解决方案概览:
          - 概览: index.md
          - 特性和收益: implementation-guide/solution-overview/features.md
          - 应用场景: implementation-guide/solution-overview/use-cases.md
          - 价格估算: implementation-guide/solution-overview/cost.md
      - 架构:
          - 架构概览: implementation-guide/architecture/architecture.md
          - AWS 服务: implementation-guide/architecture/services-in-this-solution.md
      - 开始部署:
          - 概览: implementation-guide/deployment/index.md
          - 计划部署: implementation-guide/deployment/considerations.md
          - 模型存储: implementation-guide/deployment/models.md
          - 开始部署: implementation-guide/deployment/deploy.md
          - 镜像构建: implementation-guide/deployment/image-building.md
          - EBS 缓存构建: implementation-guide/deployment/ebs-snapshot.md
          - 配置项: implementation-guide/deployment/configuration.md
      - 使用指南:
          - 文生图: implementation-guide/usage/text-to-image.md
          - 图生图: implementation-guide/usage/image-to-image.md
          - 使用ControlNet: implementation-guide/usage/controlnet.md
          - 使用LoRA: implementation-guide/usage/lora.md
          - 通知和回调: implementation-guide/usage/callback.md
      - 可观测性:
          - 查看监控: implementation-guide/observability/monitoring.md
          - 查看日志: implementation-guide/observability/logging.md
      - 常见问题: implementation-guide/faq.md
      - 故障排查: implementation-guide/trouble-shooting.md
      - 卸载解决方案: implementation-guide/uninstall.md
      - 开发者资源:
        - 源代码: implementation-guide/developer/source.md
        - API 定义: implementation-guide/developer/api-spec.md
      - 更新记录: implementation-guide/release-notes.md
  - 动手实验: "https://catalog.workshops.aws/"
